#!/bin/sh

# the plan is, this script is called with a cron job sth like so:
#minute	hour	mday	month	wday	command
# *	*	*	*	*	~/dust_wx/dust_sync

/import/home/ghz/repos/weather_tools/grab_48h /import/home/ghz/repos/dust_wx/data dust.dat
gnuplot /import/home/ghz/repos/dust_wx/dust.gnuplot
sync
# rsync this somewhere
